<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Fuerza-bruta" data-toc-modified-id="Fuerza-bruta-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Fuerza bruta</a></span><ul class="toc-item"><li><span><a href="#Apartado-A" data-toc-modified-id="Apartado-A-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Apartado A</a></span></li><li><span><a href="#Apartado-B" data-toc-modified-id="Apartado-B-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Apartado B</a></span></li></ul></li><li><span><a href="#Utilizando-Librerias-adecuadas" data-toc-modified-id="Utilizando-Librerias-adecuadas-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Utilizando Librerias adecuadas</a></span><ul class="toc-item"><li><span><a href="#Apartado-A" data-toc-modified-id="Apartado-A-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Apartado A</a></span></li><li><span><a href="#Apartado-B" data-toc-modified-id="Apartado-B-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Apartado B</a></span></li></ul></li></ul></div>

![title](".reto_nivel1.PNG")

# Ejercicio final

![img](https://github.com/mrBronnWow/Curso_Beginners/blob/master/0_Reto_de_programacion_basico/reto_nivel1.PNG?raw=true)

Importamos librerias

In [1]:
import numpy as np

## Fuerza bruta

### Apartado A

In [2]:
balls = np.array([ [1,  2,  3,  4],
                   [5,  6,  7,  8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 0]])

In [3]:
balls

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [4]:
def find_solution(balls):
    "Fuerza bruta Apartado A (intentando pensar como un novato)"
    
    # Paso el array a 1D para poder tratarlo como una lista
    balls = balls.ravel()
    sol = []
    for a in balls:
        for b in balls:
            for c in balls:
                if a!=b and a!=c and b!=c: 
                    if a!=0 and b!=0 and c!=0:
                        if a+b+c==28:
                            sol.append([a,b,c])
    return sol

In [5]:
solutions = find_solution(balls)
solutions

[[1, 12, 15],
 [1, 13, 14],
 [1, 14, 13],
 [1, 15, 12],
 [2, 11, 15],
 [2, 12, 14],
 [2, 14, 12],
 [2, 15, 11],
 [3, 10, 15],
 [3, 11, 14],
 [3, 12, 13],
 [3, 13, 12],
 [3, 14, 11],
 [3, 15, 10],
 [4, 9, 15],
 [4, 10, 14],
 [4, 11, 13],
 [4, 13, 11],
 [4, 14, 10],
 [4, 15, 9],
 [5, 8, 15],
 [5, 9, 14],
 [5, 10, 13],
 [5, 11, 12],
 [5, 12, 11],
 [5, 13, 10],
 [5, 14, 9],
 [5, 15, 8],
 [6, 7, 15],
 [6, 8, 14],
 [6, 9, 13],
 [6, 10, 12],
 [6, 12, 10],
 [6, 13, 9],
 [6, 14, 8],
 [6, 15, 7],
 [7, 6, 15],
 [7, 8, 13],
 [7, 9, 12],
 [7, 10, 11],
 [7, 11, 10],
 [7, 12, 9],
 [7, 13, 8],
 [7, 15, 6],
 [8, 5, 15],
 [8, 6, 14],
 [8, 7, 13],
 [8, 9, 11],
 [8, 11, 9],
 [8, 13, 7],
 [8, 14, 6],
 [8, 15, 5],
 [9, 4, 15],
 [9, 5, 14],
 [9, 6, 13],
 [9, 7, 12],
 [9, 8, 11],
 [9, 11, 8],
 [9, 12, 7],
 [9, 13, 6],
 [9, 14, 5],
 [9, 15, 4],
 [10, 3, 15],
 [10, 4, 14],
 [10, 5, 13],
 [10, 6, 12],
 [10, 7, 11],
 [10, 11, 7],
 [10, 12, 6],
 [10, 13, 5],
 [10, 14, 4],
 [10, 15, 3],
 [11, 2, 15],
 [11, 3, 14],


In [6]:
len(solutions)

132

In [7]:
print(f'Hay {len(solutions)} combinaciones de valores para a,b y c')

Hay 132 combinaciones de valores para a,b y c


<div class="alert alert-block alert-info"><b>Nota: </b> Esto creo que ya es complicado para los alumnos, y tecnicamente no se si se lo hemos pedido, pero puede que alguien se lie por tenerlo en cuenta,</div>

¿Pero cuantas soluciones son únicas? Porque la solucion `[1,12,15]` es la misma que `[15,12,1]` ¿Cuantas combinaciones de bolas podemos formar?

In [8]:
unique_sols = set([frozenset(x) for x in solutions])
unique_sols

{frozenset({3, 11, 14}),
 frozenset({4, 10, 14}),
 frozenset({3, 12, 13}),
 frozenset({7, 10, 11}),
 frozenset({1, 13, 14}),
 frozenset({5, 11, 12}),
 frozenset({6, 8, 14}),
 frozenset({5, 8, 15}),
 frozenset({6, 7, 15}),
 frozenset({7, 9, 12}),
 frozenset({3, 10, 15}),
 frozenset({1, 12, 15}),
 frozenset({7, 8, 13}),
 frozenset({4, 9, 15}),
 frozenset({5, 10, 13}),
 frozenset({6, 10, 12}),
 frozenset({2, 11, 15}),
 frozenset({4, 11, 13}),
 frozenset({5, 9, 14}),
 frozenset({2, 12, 14}),
 frozenset({8, 9, 11}),
 frozenset({6, 9, 13})}

In [9]:
len(unique_sols)

22

### Apartado B

In [10]:
balls = np.array( [[1,  2,  3,  4],
                   [5,  6,  7,  8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 0]])

In [11]:
balls

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [12]:
def sol_apartado_b(balls):
    solutions = find_solution(balls)
    sol_b = []
    for sol in solutions:
        a,b,c = sol
        i= np.where(balls==a)
        j= np.where(balls==b)
        k= np.where(balls==c)
        if i[0]!=j[0] and i[0]!=k[0] and j[0]!=k[0]:
            print
            sol_b.append([a,b,c])
    return sol_b

In [13]:
sol_b = sol_apartado_b(balls)
sol_b

[[1, 12, 15],
 [1, 15, 12],
 [2, 11, 15],
 [2, 12, 14],
 [2, 14, 12],
 [2, 15, 11],
 [3, 10, 15],
 [3, 11, 14],
 [3, 12, 13],
 [3, 13, 12],
 [3, 14, 11],
 [3, 15, 10],
 [4, 9, 15],
 [4, 10, 14],
 [4, 11, 13],
 [4, 13, 11],
 [4, 14, 10],
 [4, 15, 9],
 [5, 9, 14],
 [5, 10, 13],
 [5, 13, 10],
 [5, 14, 9],
 [6, 9, 13],
 [6, 13, 9],
 [9, 4, 15],
 [9, 5, 14],
 [9, 6, 13],
 [9, 13, 6],
 [9, 14, 5],
 [9, 15, 4],
 [10, 3, 15],
 [10, 4, 14],
 [10, 5, 13],
 [10, 13, 5],
 [10, 14, 4],
 [10, 15, 3],
 [11, 2, 15],
 [11, 3, 14],
 [11, 4, 13],
 [11, 13, 4],
 [11, 14, 3],
 [11, 15, 2],
 [12, 1, 15],
 [12, 2, 14],
 [12, 3, 13],
 [12, 13, 3],
 [12, 14, 2],
 [12, 15, 1],
 [13, 3, 12],
 [13, 4, 11],
 [13, 5, 10],
 [13, 6, 9],
 [13, 9, 6],
 [13, 10, 5],
 [13, 11, 4],
 [13, 12, 3],
 [14, 2, 12],
 [14, 3, 11],
 [14, 4, 10],
 [14, 5, 9],
 [14, 9, 5],
 [14, 10, 4],
 [14, 11, 3],
 [14, 12, 2],
 [15, 1, 12],
 [15, 2, 11],
 [15, 3, 10],
 [15, 4, 9],
 [15, 9, 4],
 [15, 10, 3],
 [15, 11, 2],
 [15, 12, 1]]

In [14]:
len(sol_b)

72

In [15]:
unique_sols_b = set([frozenset(x) for x in sol_b])
unique_sols_b

{frozenset({3, 11, 14}),
 frozenset({5, 9, 14}),
 frozenset({2, 12, 14}),
 frozenset({4, 10, 14}),
 frozenset({5, 10, 13}),
 frozenset({3, 12, 13}),
 frozenset({3, 10, 15}),
 frozenset({2, 11, 15}),
 frozenset({1, 12, 15}),
 frozenset({4, 11, 13}),
 frozenset({6, 9, 13}),
 frozenset({4, 9, 15})}

In [16]:
len(unique_sols_b)

12

Creo que esta forma de pensar es muy complicada para el primer ejercicio :S

## Utilizando Librerias adecuadas

### Apartado A

In [29]:
from itertools import combinations

In [51]:
arr = np.arange(1,15+1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
comb=list(combinations(arr, r=3))
comb

[(1, 2, 3),
 (1, 2, 4),
 (1, 2, 5),
 (1, 2, 6),
 (1, 2, 7),
 (1, 2, 8),
 (1, 2, 9),
 (1, 2, 10),
 (1, 2, 11),
 (1, 2, 12),
 (1, 2, 13),
 (1, 2, 14),
 (1, 2, 15),
 (1, 3, 4),
 (1, 3, 5),
 (1, 3, 6),
 (1, 3, 7),
 (1, 3, 8),
 (1, 3, 9),
 (1, 3, 10),
 (1, 3, 11),
 (1, 3, 12),
 (1, 3, 13),
 (1, 3, 14),
 (1, 3, 15),
 (1, 4, 5),
 (1, 4, 6),
 (1, 4, 7),
 (1, 4, 8),
 (1, 4, 9),
 (1, 4, 10),
 (1, 4, 11),
 (1, 4, 12),
 (1, 4, 13),
 (1, 4, 14),
 (1, 4, 15),
 (1, 5, 6),
 (1, 5, 7),
 (1, 5, 8),
 (1, 5, 9),
 (1, 5, 10),
 (1, 5, 11),
 (1, 5, 12),
 (1, 5, 13),
 (1, 5, 14),
 (1, 5, 15),
 (1, 6, 7),
 (1, 6, 8),
 (1, 6, 9),
 (1, 6, 10),
 (1, 6, 11),
 (1, 6, 12),
 (1, 6, 13),
 (1, 6, 14),
 (1, 6, 15),
 (1, 7, 8),
 (1, 7, 9),
 (1, 7, 10),
 (1, 7, 11),
 (1, 7, 12),
 (1, 7, 13),
 (1, 7, 14),
 (1, 7, 15),
 (1, 8, 9),
 (1, 8, 10),
 (1, 8, 11),
 (1, 8, 12),
 (1, 8, 13),
 (1, 8, 14),
 (1, 8, 15),
 (1, 9, 10),
 (1, 9, 11),
 (1, 9, 12),
 (1, 9, 13),
 (1, 9, 14),
 (1, 9, 15),
 (1, 10, 11),
 (1, 10, 12),
 (1, 10, 13)

In [53]:
sol_A = []
for posible_sol in comb:
    a,b,c = posible_sol
    if a!=0 and b!=0 and c!=0:
        if a+b+c==28:
            sol_A.append([a,b,c])

In [54]:
sol_A

[[1, 12, 15],
 [1, 13, 14],
 [2, 11, 15],
 [2, 12, 14],
 [3, 10, 15],
 [3, 11, 14],
 [3, 12, 13],
 [4, 9, 15],
 [4, 10, 14],
 [4, 11, 13],
 [5, 8, 15],
 [5, 9, 14],
 [5, 10, 13],
 [5, 11, 12],
 [6, 7, 15],
 [6, 8, 14],
 [6, 9, 13],
 [6, 10, 12],
 [7, 8, 13],
 [7, 9, 12],
 [7, 10, 11],
 [8, 9, 11]]

In [55]:
len(sol_A)

22

### Apartado B

In [56]:
balls = np.array([ [1,  2,  3,  4],
                   [5,  6,  7,  8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 0]])

In [57]:
balls

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# Es la misma que está arriba
def sol_apartado_b(balls):
    solutions = find_solution(balls)
    sol_b = []
    for sol in solutions:
        a,b,c = sol
        i= np.where(balls==a)
        j= np.where(balls==b)
        k= np.where(balls==c)
        if i[0]!=j[0] and i[0]!=k[0] and j[0]!=k[0]:
            print
            sol_b.append([a,b,c])
    return sol_b